(define (cube x) (* x x x))
(define (improve guess target)
  (/ (+ (/ target (square guess)) (* 2 guess)) 3))
(define (square x) (* x x))
(define (cubert-itr guess target)
  (if (good-enough? guess target)
    guess
    (cubert-itr (improve guess target) target)))
(define (cubert target)
  (cubert-itr 1.0 target))
(define (abs x)
  (if (< x 0)
    (- x)
    x))
(define (good-enough? guess target)
  (< (abs (- (cube guess) target)) .01))
